---
- hosts: default
  become: true
  tasks:
  - name: Install Dependencies
    apt:
      name: '{{ item }}'
      state: present
    loop:
      - nginx
      - docker.io
  - name: Ensure Services is running
    service:
      name: '{{ item }}'
      state: started
