---
- hosts: all
  become: true
  
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
  
  - name: Ensure a list of yum packages are installed
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - yum-utils
      - amazon-linux-extras
  
  - name: Add extras repository
    shell: yum-config-manager --enable extras

  - name: Install nginx
    shell: amazon-linux-extras install nginx1.12=latest -y
    notify:
      - Enable Nginx service at startup
  
  - name: Check nginx version 
    command: sudo nginx -v
    register: nginx_version
  - debug:
      var: nginx_version.stderr
  
  - name: Install docker-ce (centos) via amazon-linux-extras packages
    shell: amazon-linux-extras install docker=latest -y
    notify:
      - Enable Docker CE service at startup
  
  - name: Check docker version 
    command: sudo docker --version
    register: docker_version
  - debug:
      var: docker_version.stdout
  
  - name: Check installed service status
    service_facts:
    register: services_state
  - debug:
      var: services_state.ansible_facts.services['nginx.service']
  - debug:
      var: services_state.ansible_facts.services['docker.service']
  
  handlers:
  - name: Enable Docker CE service at startup
    service:
      name: docker
      state: started
      enabled: yes
    when: docker_version.changed == true
  
  - name: Enable Nginx service at startup
    service:
      name: nginx
      state: started
      enabled: yes
    when: nginx_version.changed == true