---
- hosts: all
  become: true
  
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
  
  - name: Ensure a list of yum packages are installed
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - yum-utils
      - amazon-linux-extras
  
  - name: Add extras repository
    shell: yum-config-manager --enable extras

  - name: Install nginx
    shell: amazon-linux-extras install nginx1.12=latest -y
  
  - name: Check nginx version 
    command: sudo nginx -v
    register: nginx_version
  - debug:
      var: nginx_version
  
  - name: Install docker-ce (centos) via amazon-linux-extras packages
    shell: amazon-linux-extras install docker=latest -y
  
  - name: Check docker version 
    command: sudo docker --version
    register: docker_version
  - debug:
      var: docker_version

  - name: Enable Docker CE service at startup
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: Check docker service status
    command: sudo systemctl status docker | grep active
    register: docker_status
  - debug:
      var: docker_status

  - name: Enable Nginx service at startup
    service:
      name: nginx
      state: started
      enabled: yes
  
  - name: Check Nginx service status
    command: sudo systemctl status nginx | grep active
    register: nginx_status
  - debug:
      var: nginx_status