---
# vars file 
linux_distribution: ubuntu
nginx_version: latest
docker_version: latest
docker_GPG_key: https://download.docker.com/linux/ubuntu/gpg
docker_repository: https://download.docker.com/linux/ubuntu
packages:
  - yum-utils
  - amazon-linux-extras
