---
- name: Update all packages (centos)
  yum:
    name: '*'
    state: latest
    update_only: yes
  when: linux_distribution == "centos"

- name: Ensure a list of yum packages are installed (centos)
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - yum-utils
    - amazon-linux-extras
  when: linux_distribution == "centos"

- name: Add extras repository (centos)
  shell: yum-config-manager --enable extras
  when: linux_distribution == "centos"

- name: Install nginx (centos)
  shell: amazon-linux-extras install nginx1.12=latest -y
  when: linux_distribution == "centos"
  notify:
    - Enable Nginx service at startup

- name: Install nginx (ubuntu)
  apt:
    name: nginx
    state: present
  when: linux_distribution == "ubuntu"