---
- hosts: all
  become: true

  vars:
    linux_distribution: centos
  
  tasks:
  - name: Update all packages (centos)
    yum:
      name: '*'
      state: latest
      update_only: yes
    when: linux_distribution == "centos"
  
  - name: Ensure a list of yum packages are installed (centos)
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - yum-utils
      - amazon-linux-extras
    when: linux_distribution == "centos"
  
  - name: Add extras repository (centos)
    shell: yum-config-manager --enable extras
    when: linux_distribution == "centos"

  - name: Install nginx (centos)
    shell: amazon-linux-extras install nginx1.12=latest -y
    when: linux_distribution == "centos"
    notify:
      - Enable Nginx service at startup
  
  - name: Install nginx (ubuntu)
    apt:
      name: nginx
      state: present
    when: linux_distribution == "ubuntu"
  
  - name: Check nginx version 
    command: sudo nginx -v
    register: nginx_version
  - debug:
      var: nginx_version.stderr
  
  - name: Install docker-ce (centos)
    shell: amazon-linux-extras install docker=latest -y
    when: linux_distribution == "centos"
    notify:
      - Enable Docker CE service at startup
  
  - name: Add Docker GPG apt Key (ubuntu)
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    when: linux_distribution == "ubuntu"
  
  - name: Add Docker Repository (ubuntu)
    apt_repository:
      repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
      state: present
    when: linux_distribution == "ubuntu"
  
  - name: Install docker-ce (ubuntu)
    apt:
      name: docker-ce
      update_cache: true
    when: linux_distribution == "ubuntu"
  
  - name: Check docker version 
    command: sudo docker --version
    register: docker_version
  - debug:
      var: docker_version.stdout
  
  - name: Check installed service status
    service_facts:
    register: services_state
  - debug:
      var: services_state.ansible_facts.services['nginx.service']
  - debug:
      var: services_state.ansible_facts.services['docker.service']
  
  handlers:
  - name: Enable Docker CE service at startup
    service:
      name: docker
      state: started
      enabled: yes
    when: docker_version.changed == true
  
  - name: Enable Nginx service at startup
    service:
      name: nginx
      state: started
      enabled: yes
    when: nginx_version.changed == true
