---
- name: Deploy Packer Image 
  hosts: all
  become: true

  tasks:
  - include_vars: ./vars/main.yml
  - include_tasks: ./tasks/nginx.yml
  - include_tasks: ./tasks/docker.yml
  
  - name: Flush handlers
    meta: flush_handlers

  - include_tasks: ./tests/debug.yml
  
  handlers:
  - name: Enable Docker CE service at startup
    service:
      name: docker
      state: started
      enabled: yes

  - name: Enable Nginx service at startup
    service:
      name: nginx
      state: started
      enabled: yes